--INSERT INTO TB_USER (ID, EMAIL, NAME, PASSWORD) VALUES (1, 'root@localhost', 'root', '123456');
INSERT INTO TB_PROFILE  (ID, ROLE) VALUES (1, 'USER');
INSERT INTO TB_PROFILE  (ID, ROLE) VALUES (2, 'ADMIN');
INSERT INTO TB_PROFILE  (ID, ROLE) VALUES (3, 'DONOR');
INSERT INTO TB_PROFILE  (ID, ROLE) VALUES (4, 'GRANTEE');
INSERT INTO TB_PROFILE  (ID, ROLE) VALUES (5, 'NGO');
--INSERT INTO TB_USER_PROFILE (USER_ID, PROFILE_ID) VALUES (1, 1)