INSERT INTO TB_USUARIO (ID, EMAIL, NAME, PASSWORD) VALUES (1, 'root@localhost', 'root', '123456');
INSERT INTO TB_PERFIL  (ID, ROLE) VALUES (1, 'USER');
INSERT INTO TB_PERFIL  (ID, ROLE) VALUES (2, 'ADMIN');
INSERT INTO TB_USUARIO_PERFIL (USUARIO_ID, PERFIL_ID) VALUES (1, 1)